// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8Yn8Z_KZWX1wmzV_-NtZYM-Ul3WCAbE',
    appId: '1:133224842884:web:8810b71de7635da23364d1',
    messagingSenderId: '133224842884',
    projectId: 'hostel-efdfa',
    authDomain: 'hostel-efdfa.firebaseapp.com',
    storageBucket: 'hostel-efdfa.appspot.com',
    measurementId: 'G-KGH22TJ1GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnuE1h__iJJt_h_Wu50jtF66vtpC47TwM',
    appId: '1:133224842884:android:cc13a2692268b7943364d1',
    messagingSenderId: '133224842884',
    projectId: 'hostel-efdfa',
    storageBucket: 'hostel-efdfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7iy8UFuYmjPvlWbSVJAIrQ5bmfs0W6U',
    appId: '1:133224842884:ios:2614327f7c65c4d23364d1',
    messagingSenderId: '133224842884',
    projectId: 'hostel-efdfa',
    storageBucket: 'hostel-efdfa.appspot.com',
    iosBundleId: 'com.example.hostelAdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7iy8UFuYmjPvlWbSVJAIrQ5bmfs0W6U',
    appId: '1:133224842884:ios:da4a4d6ce922684a3364d1',
    messagingSenderId: '133224842884',
    projectId: 'hostel-efdfa',
    storageBucket: 'hostel-efdfa.appspot.com',
    iosBundleId: 'com.example.hostelAdd.RunnerTests',
  );
}
